### ISSUE TITLE
Add support for upgrade and partial downloads

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/sphinxext-pwa#9] opened 2022-03-08 22:54 UTC
Currently, partial downloads irreparably break the PWA's functionality.

**Comment by Daltz333** [comment] 2022-03-08 23:33
I cannot actually reproduce this on Android. On Android, it redoes the "install" event since the "activate" event is only triggered when "install" is done.

**Comment by Daltz333** [comment] 2022-03-09 16:07
I have confirmed that partial downloads and upgrades both function as intended. Tested on Windows 11 Microsoft Edge. I'm going to go ahead and close this issue. If this is iOS specific, please open a new issue with additional details.

**Closed as completed by Daltz333** 2022-03-09 16:07 UTC
Labels: unable to reproduce
